apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwc-python-app
  labels:
    app: pwc-python-app
spec:
  template:
    metadata:
      labels:
        app: pwc-python-app
    spec:
      containers:
      - name: python-container
        image: 586710795513.dkr.ecr.eu-west-1.amazonaws.com/default/python:latest
        ports:
        - containerPort: 80

  replicas: 2
  selector:
    matchLabels:
      app: pwc-python-app
